
<?php
/**
 * Implements hook_menu
 */
function servicehired_api_menu() {

  // Creates orders.
  $items['developers/new_user'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'servicehired_order_create',
    'file' => 'includes/servicehired_account.rest.inc',
    'access arguments' => array('access content')
  );

  $items['dash'] = array(
    'page callback' => 'dashboard_page',
    'access arguments' => array('access content')
  );

  // Creates comments through api.
  $items['developers/get_orders'] = array(
    'access arguments' => array('access content'),
    'page callback' => 'servicehired_get_orders'
  );

  return $items;
}

function dashboard_page(){
  return theme('dashboard_page');
}

/**
 * Implements hook_theme()
 */
function servicehired_api_theme() {
  return array(
    'dashboard_page' => array(
      'render element' => 'elements',
      'template' => 'templates/dashboard',
    ),
  );
}


function servicehired_get_orders() {
  global $user;
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'order')
    ->propertyCondition('uid', $user->uid);
  $result = $query->execute();
  $nids = array_keys($result['node']);
  $nodes = node_load_multiple($nids);
  $i = 0;
  $key = array();
  foreach ($nodes as $node) {
    $i ++;
    $key[$i]['url'] = 'node/'.$node->nid;
    $key[$i]['title'] = $node->title;
    $key[$i]['created'] = date('d/m/Y', $node->created);
    $key[$i]['body'] = $node->body['und'][0]['value'];
    $key[$i]['status'] = $node->field_status['und'][0]['value'];
  }

  return $key;
}


function status_bar_format($status) {
  $html = '<div class="status-bar status-'.$status.'">
  <div class="bar first">Order made</div>
  <div class="bar second">Confirmed</div>
  <div class="bar last">Paid</div >
  </div>';

  return $html;
}

function servicehired_orders_format() {
  $key = servicehired_get_orders();
  $html = '';

  foreach ($key as $res){
    $html .= '<a href="'.$res['url'].'">
    <div class="result">
    <div class="insider">
    <div class="res-title">'.$res['title'].'</div>
    <div class="status">'.status_bar_format($res['status']).'</div>
    <div class="created">'.$res['created'].'</div>
    </div></div></a>';
  }
  return $html;
}