
<?php
/**
 * Implements hook_menu
 */
function servicehired_api_menu() {

  // Creates orders.
  $items['developers/new_user'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'servicehired_order_create',
    'file' => 'includes/servicehired_account.rest.inc',
    'access arguments' => array('access content')
  );

  $items['dash'] = array(
    'page callback' => 'dashboard_page',
    'access arguments' => array('access content')
  );



  return $items;
}

function dashboard_page(){
  return theme('dashboard_page');
}

/**
 * Implements hook_theme()
 */
function servicehired_api_theme() {
  return array(
    'dashboard_page' => array(
      'render element' => 'elements',
      'template' => 'templates/dashboard',
    ),
  );
}
